name: movie_app
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

# SERVICE
  dio: ^4.0.6

# PARSING
  json_serializable: ^6.3.1
  json_annotation: ^4.6.0

# UI PROVIDER
  cupertino_icons: ^1.0.2

# STATE MANAGEMENT
  bloc: ^8.0.3
  flutter_bloc: ^8.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
# BUILD
  build_runner: ^2.1.8

# ANALYSIS
  flutter_lints: ^1.0.0

# TEST
  flutter_driver:
    sdk: flutter
  test: 1.21.4

flutter:
  uses-material-design: true

  assets:
    - assets/images/