name: movie_app
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

# SERVICE
  http: ^0.13.4
# PARSING
  json_serializable: ^6.3.1
  json_annotation: ^4.6.0
  cupertino_icons: ^1.0.2
# STATE MANAGEMENT
  get_it: ^7.2.0
  bloc: ^8.0.3
  flutter_bloc: ^8.0.1
  provider: ^6.0.2
  equatable: ^2.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
# BUILD
  build_runner: ^2.1.8
  flutter_lints: ^1.0.0
flutter:

  uses-material-design: true